[package]
name = "ok-wasm"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "WebAssembly bindings for the offkilter kernel"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
ok-math = { workspace = true }
ok-sketch = { workspace = true }
ok-mesh = { workspace = true }
ok-brep = { workspace = true }
ok-model = { workspace = true }
ok-sheet = { workspace = true }
ok-step = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
wasm-bindgen = "0.2.128"
