[package]
name = "ok-mesh"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Triangle meshes and tessellation for the offkilter kernel"

[dependencies]
ok-math = { workspace = true }
ok-sketch = { workspace = true }
serde = { workspace = true }
earcutr = "0.4"
